# Generated by Django 5.0 on 2023-12-30 22:36

import django.core.validators
import djangoWorkingFolder.myPlantApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantType', models.CharField(choices=[('outdoor', 'Outdoor Plants'), ('indoor', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), djangoWorkingFolder.myPlantApp.models.ValidateOnlyLetters])),
                ('imageUrl', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('firstName', models.CharField(max_length=20, validators=[djangoWorkingFolder.myPlantApp.models.ValidateFirstCapitalLetter])),
                ('lastName', models.CharField(max_length=20, validators=[djangoWorkingFolder.myPlantApp.models.ValidateFirstCapitalLetter])),
                ('profilePicture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
