# Generated by Django 5.0 on 2024-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(max_length=25)),
                ('sourceUrl', models.URLField()),
                ('dataSource', models.CharField(choices=[('S-2', 'Sentinel-2'), ('L-8', 'Landsat 8-9'), ('Copernicus', 'Copernicus Services')])),
                ('trueColourImage', models.ImageField(upload_to='')),
                ('falseColourImage', models.ImageField(upload_to='')),
                ('NDVIimage', models.ImageField(upload_to='')),
                ('imageDate', models.DateField()),
                ('publicationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
