# Generated by Django 5.0 on 2024-01-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofiauniproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimage',
            name='NDVIimage',
            field=models.ImageField(upload_to='ndvi_images/'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='falseColourImage',
            field=models.ImageField(upload_to='false_colour_images/'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='publicationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='trueColourImage',
            field=models.ImageField(upload_to='true_colour_images/'),
        ),
    ]
